# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ba910195d075500369c205720c911c7406598b539a3856719b79aafc0a2d5a778b2088162c56a461d724759b5c5173f1a98d6f7ce4398243ac157bde4b74b7

test:
  secret_key_base: 9d55c6745fa406cd060eabb2690f37c505207db09aa53f692ec3888d8b955bc001f3c7d8bc105a21da6a06d51057fdbf92c2a3672007e28dbd88e9ab8315029a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
